-- Generated INSERT for directory_entries from index.html DATA
INSERT INTO directory_entries (
  entry_id,
  display_name,
  description,
  primary_category,
  category_keys
)
VALUES
  ('מערך_בריאות_הנפש_במשרד_הביטחון_10', 'מערך בריאות הנפש במשרד הביטחון', 'קבלת סיוע נפשי מיידי', 'emergency', ARRAY['emergency', 'helplines', 'mod']::text[]),
  ('נפש_אחת_בישראל_אגף_השיקום_משרד_הבטחון_11', '"נפש אחת בישראל"
(אגף השיקום, משרד הבטחון)', 'קו המעניק תמיכה נפשית ראשונית', 'emergency', ARRAY['emergency', 'helplines', 'mod', 'trauma']::text[]),
  ('עמותת_ער_ן_עזרה_ראשונה_נפשית_20', 'עמותת ער"ן (עזרה ראשונה נפשית)', 'קו סיוע והכוונה', 'emergency', ARRAY['emergency', 'helplines']::text[]),
  ('מרכזי_חוסן_30', 'מרכזי חוסן', 'רשימת מרכזי חוסן ברחבי הארץ', 'emergency', ARRAY['emergency']::text[]),
  ('avnei_chein_77', 'Avnei Chein', 'Israel''s Emergency Mental Health Resources During War - Comprehensive list of mental health resources', 'emergency', ARRAY['emergency', 'portals', 'populations']::text[]),
  ('אגף_השיקום_משרד_הבטחון_39', 'אגף השיקום, משרד הבטחון', 'בית בטוח לטיפול מיידי - חלופת אשפוז', 'emergency', ARRAY['emergency', 'mod', 'alternatives', 'trauma']::text[]),
  ('שרן_רפואה_עד_הבית_40', 'שרן רפואה עד הבית', 'צוות משבר (חלופה לחדר מיון)', 'emergency', ARRAY['emergency', 'alternatives']::text[]),
  ('בנפש_בריאה_משרד_הבריאות_13', 'בנפש בריאה - משרד הבריאות', 'קווי סיוע והכוונה', 'helplines', ARRAY['helplines', 'portals']::text[]),
  ('מוקד_הסיוע_של_משרד_החינוך_15', 'מוקד הסיוע של משרד החינוך', 'מוקד סיוע רגשי-חברתי להורים ולתלמידים', 'helplines', ARRAY['helplines']::text[]),
  ('ביטוח_לאומי_14', 'ביטוח לאומי', 'רשימת מוקדי הטיפול ומרכזי החוסן', 'helplines', ARRAY['helplines', 'portals']::text[]),
  ('נט_ל_נפגעי_טראומה_על_רקע_לאומי_21', 'נט"ל (נפגעי טראומה על רקע לאומי)', 'תמיכה נפשית ותעסוקתית לנפגעי טראומה ממלחמה וטרור', 'helplines', ARRAY['helplines', 'mod', 'trauma', 'families']::text[]),
  ('סיוע_והקשבה_ברשת_סהר_22', 'סיוע והקשבה ברשת (סהר)', 'קו סיוע והכוונה', 'helplines', ARRAY['helplines']::text[]),
  ('מטיבת_א_מרכז_טיפול_יעוץ_במשפחה_תורני_24', 'מטיבת"א (מרכז טיפול יעוץ במשפחה תורני)

', 'מוקדי סיוע
מרכז טיפול
ועוד', 'helplines', ARRAY['helplines', 'portals', 'therapists', 'populations']::text[]),
  ('מוקד_call_לנפש_25', 'מוקד CALL לנפש', 'תמיכה ואוזן קשבת לבני משפחה למתמודדי נפש', 'helplines', ARRAY['helplines', 'families']::text[]),
  ('avnei_chein_76', 'Avnei Chein', 'Crisis Support, Family Support, Family & Sibling Therapy, Legal Support, Mentors and Volunteers, Network of Professionals', 'helplines', ARRAY['helplines', 'therapists', 'families', 'populations']::text[]),
  ('ידידי_נפש_עזר_מציון_26', 'ידידי נפש (עזר מציון)', 'קו ייעוץ ותמיכה - בימים א-ה בשעות 10:00-13:00 ו-16:00-22:00', 'helplines', ARRAY['helplines']::text[]),
  ('עמותת_בית_חם_60', 'עמותת בית חם', 'מידע, ייעוץ ותמיכה
מרכזי טיפול
מרכזי שיקום', 'helplines', ARRAY['helplines', 'portals', 'moh']::text[]),
  ('עמותת_בית_חם_61', 'עמותת בית חם', 'מידע, ייעוץ ותמיכה', 'helplines', ARRAY['helplines', 'portals', 'moh']::text[]),
  ('הדספייס_63', 'הדספייס', 'תמיכה לנוער וצעירים', 'helplines', ARRAY['helplines', 'treatments', 'treatments_therapy', 'youth']::text[]),
  ('אגף_השיקום_משרד_הבטחון_12', 'אגף השיקום, משרד הבטחון', 'זכויות למתמודדים עם פגיעה נפשית', 'portals', ARRAY['portals', 'rights', 'mod']::text[]),
  ('פורטל_בריאות_הנפש_בישראל_16', 'פורטל בריאות הנפש בישראל', 'שירותים למתמודד
אינדקס מטפלים
פורומים
ועוד ועוד', 'portals', ARRAY['portals', 'therapists']::text[]),
  ('החלמה_הנגשת_מידע_למתמודד_נפש_ומשפחתו_17', 'החלמה - הנגשת מידע למתמודד נפש ומשפחתו', NULL, 'portals', ARRAY['portals', 'families']::text[]),
  ('get_help_israel_18', 'GET HELP Israel', 'Provides English-speakers with access to verified mental health specialists as well as resources and information on navigating the mental health system in Israel', 'portals', ARRAY['portals', 'therapists', 'populations']::text[]),
  ('בטיפולנט_19', 'בטיפולנט', 'אינדקס שירותים למענה נפשי וטיפול בפוסט-טראומה', 'portals', ARRAY['portals', 'mod', 'therapists', 'trauma']::text[]),
  ('רי_ל_הרשת_הישראלית_לחוסן_21', 'רי"ל - הרשת הישראלית לחוסן', 'רשת לאומית לחוסן נפשי המאפשרת יצירת כלים אינטראקטיביים מותאמים לקהלי יעד שונים', 'portals', ARRAY['portals']::text[]),
  ('סיוע_והקשבה_ברשת_סהר_23', 'סיוע והקשבה ברשת (סהר)', 'אינדקס שירותים', 'portals', ARRAY['portals']::text[]),
  ('רגיש_לי_27', 'רגיש לי', 'אינדקס שירותים למתמודדי נפש', 'portals', ARRAY['portals']::text[]),
  ('זה_מגיע_לכם_ד_ר_גילי_תמיר_59', 'זה מגיע לכם - ד"ר גילי תמיר ', 'מיצוי זכויות', 'portals', ARRAY['portals', 'rights']::text[]),
  ('כל_זכות_85', 'כל זכות', 'מדריך מיצוי זכויות למתמודדי נפש ובני משפחותיהם', 'rights', ARRAY['rights']::text[]),
  ('כל_זכות_82', 'כל זכות', 'קביעת נכות למתמודדי נפש', 'rights', ARRAY['rights']::text[]),
  ('כל_זכות_83', 'כל זכות', 'קצבת שירותים מיוחדים למתמודדי נפש', 'rights', ARRAY['rights']::text[]),
  ('כל_זכות_84', 'כל זכות', 'סל שיקום למתמודדי נפש', 'rights', ARRAY['rights']::text[]),
  ('ביטוח_לאומי_1', 'ביטוח לאומי', 'קצבת נכות למתמודדי נפש', 'rights', ARRAY['rights']::text[]),
  ('ביטוח_לאומי_2', 'ביטוח לאומי', 'שירותים מיוחדים (שר"מ)', 'rights', ARRAY['rights']::text[]),
  ('ביטוח_לאומי_3', 'ביטוח לאומי', 'קצבת סיעוד', 'rights', ARRAY['rights']::text[]),
  ('יד_מכוונת_4', 'יד מכוונת', 'ייעוץ והכנה בחינם לוועדה הרפואית', 'rights', ARRAY['rights']::text[]),
  ('משרד_הבריאות_5', 'משרד הבריאות', 'סל שיקום', 'rights', ARRAY['rights', 'moh', 'rehabilitation']::text[]),
  ('מדברים_על_סל_שיקום_57', 'מדברים על סל שיקום', 'קבוצה בפייסבוק', 'rights', ARRAY['rights', 'rehabilitation', 'facebook']::text[]),
  ('בלב_ובנפש_עזר_מציון_68', 'בלב ובנפש (עזר מציון)
', 'סיוע למשפחות של מתמודדי נפש', 'rights', ARRAY['rights', 'rehabilitation', 'families']::text[]),
  ('משרד_הבריאות_13', 'משרד הבריאות', 'קווי סיוע והכוונה', 'moh', ARRAY['moh']::text[]),
  ('משרד_הבריאות_מינהל_בריאות_הנפש_15', 'משרד הבריאות, מינהל בריאות הנפש', 'מרכזי תמיכה רגשית ונפשית
', 'moh', ARRAY['moh', 'rehabilitation']::text[]),
  ('המרכז_הירושלמי_לבריאות_הנפש_כפר_שאול_איתנים_78', 'המרכז הירושלמי לבריאות הנפש (כפר שאול-איתנים)', 'המרכז מעניק רצף טיפולי למגוון הפרעות הנפש, בכל הגילאים, למצבים פסיכוטיים חריפים, מצבים ממושכים עם דגש שיקומי ושירות קהילתי. מערך הטיפול כולל את כל סוגי הטיפולים הביולוגיים המקובלים (תרופות חדישות לסוגיהן, חדר סנוסלן – גרייה רב חושית ונזעי חשמל), טיפול זוגי ומשפחתי, פסיכותראפיה פרטנית וקבוצתית, טיפול באומנות וריפוי בעיסוק.', 'moh', ARRAY['moh', 'hospitalization', 'alternatives', 'rehabilitation', 'treatments', 'treatments_psychiatry']::text[]),
  ('אנוש_6', 'אנוש', 'שירותי סל שיקום', 'moh', ARRAY['moh', 'rehabilitation']::text[]),
  ('קידום_7', 'קידום', 'שירותי סל שיקום', 'moh', ARRAY['moh', 'rehabilitation', 'populations']::text[]),
  ('ידיד_נפש_8', 'ידיד נפש', 'שירותי סל שיקום', 'moh', ARRAY['moh', 'rehabilitation']::text[]),
  ('אור_לנפש_9', 'אור לנפש', 'שירותי סל שיקום', 'moh', ARRAY['moh', 'rehabilitation']::text[]),
  ('משרד_הבריאות_35', 'משרד הבריאות', 'אינדקס פסיכולוגים מורשים', 'moh', ARRAY['moh', 'therapists']::text[]),
  ('מהפנטים_36', 'מהפנטים', 'אינדקס משרד הבריאות - מהפנטים בעלי רשיון', 'moh', ARRAY['moh', 'therapists', 'treatments', 'treatments_others']::text[]),
  ('מילם_מרכז_ייעוץ_למשפחות_מתמודדים_52', 'מילם (מרכז ייעוץ למשפחות מתמודדים)', 'מרכזי ייעוץ, הכוונה, סיוע והדרכה למשפחות מתמודדים', 'moh', ARRAY['moh', 'families']::text[]),
  ('עמותת_בית_חם_62', 'עמותת בית חם', 'מרפאות לבריאות הנפש
', 'moh', ARRAY['moh']::text[]),
  ('שרן_רפואה_עד_הבית_42', 'שרן רפואה עד הבית', 'ייעוץ פסיכיאטרי מקוון', 'mod', ARRAY['mod', 'therapists', 'treatments', 'treatments_psychiatry']::text[]),
  ('שרן_רפואה_עד_הבית_44', 'שרן רפואה עד הבית', 'אשפוז בית פסיכיאטרי', 'mod', ARRAY['mod', 'hmo', 'alternatives']::text[]),
  ('כללית_28', 'כללית', 'מרפאות בריאות הנפש - פסיכיאטר ופסיכותרפיה', 'hmo', ARRAY['hmo']::text[]),
  ('מכבי_29', 'מכבי', 'מרפאות בריאות הנפש - פסיכיאטר ופסיכותרפיה', 'hmo', ARRAY['hmo']::text[]),
  ('מאוחדת_80', 'מאוחדת', 'מרפאות בריאות הנפש - פסיכיאטר ופסיכותרפיה', 'hmo', ARRAY['hmo']::text[]),
  ('לאומית_81', 'לאומית', 'מרפאות בריאות הנפש - פסיכיאטר ופסיכותרפיה', 'hmo', ARRAY['hmo']::text[]),
  ('צבר_רפואה_48', 'צבר רפואה', 'אשפוז בית פסיכיאטרי', 'hmo', ARRAY['hmo', 'alternatives']::text[]),
  ('שרן_רפואה_עד_הבית_79', 'שרן רפואה עד הבית', 'תוכנית טיפול ביתי ממושך למתמודדים עם מחלת נפש חמורה', 'hmo', ARRAY['hmo', 'alternatives']::text[]),
  ('שרן_רפואה_עד_הבית_46', 'שרן רפואה עד הבית', 'פסיכותרפיה מקוונת', 'hmo', ARRAY['hmo', 'therapists', 'treatments', 'treatments_therapy']::text[]),
  ('בתי_חולים_פסיכיאטריים_ומחלקות_פסיכיאטריות_בבתי_חולים_כלליים_38', 'בתי חולים פסיכיאטריים ומחלקות פסיכיאטריות בבתי חולים כלליים', 'אשפוז פסיכיאטרי', 'hospitalization', ARRAY['hospitalization']::text[]),
  ('שרן_רפואה_עד_הבית_45', 'שרן רפואה עד הבית', 'הקול שבפנים – טיפול ביתי לצעירים במצבי משבר נפשי', 'alternatives', ARRAY['alternatives', 'families', 'youth']::text[]),
  ('בתים_מאזנים_53', 'בתים מאזנים', 'חלופת אשפוז', 'alternatives', ARRAY['alternatives']::text[]),
  ('נוער_הקואליציה_קואליציית_הארגונים_הדתיים_למען_בריאות_הנפש_64', 'נוער הקואליציה
(קואליציית הארגונים הדתיים למען בריאות הנפש)', 'קבוצה חברתית לנערים ונערות מתמודדי ומתמודדות נפש דתיים ודתלשים', 'rehabilitation', ARRAY['rehabilitation', 'youth', 'populations']::text[]),
  ('מרכז_יה_ל_ייעוץ_והכוונה_למשפחות_66', 'מרכז יה״ל- ייעוץ והכוונה למשפחות', 'ייעוץ והכוונה למשפחות בתחום בריאות הנפש', 'rehabilitation', ARRAY['rehabilitation', 'families']::text[]),
  ('איכות_בשיקום_67', 'איכות בשיקום', 'סיוע למתמודדי נפש דרך שילובם בקהילה תוך ליווי מקצועי אישי', 'rehabilitation', ARRAY['rehabilitation']::text[]),
  ('דיאלוג_פתוח_בישראל_דפ_י_69', 'דיאלוג פתוח בישראל (דפ"י)', 'טיפול משפחתי-מערכתי למצבי משבר', 'rehabilitation', ARRAY['rehabilitation', 'treatments', 'treatments_therapy']::text[]),
  ('עמך_המרכז_הישראלי_לתמיכה_נפשית_וחברתית_בניצולי_השואה_והדור_ה_70', 'עמך - המרכז הישראלי לתמיכה נפשית וחברתית בניצולי השואה והדור השני ', 'תמיכה נפשית וחברתית בניצולי השואה והדור השני ', 'rehabilitation', ARRAY['rehabilitation', 'populations']::text[]),
  ('עמותת_לשמה_71', 'עמותת לשמה', 'לשילוב מתמודדים והעצמה בבריאות הנפש', 'rehabilitation', ARRAY['rehabilitation']::text[]),
  ('זה_בנפשי_72', 'זה בנפשי', 'תמיכה בילדים ונוער המטופלים במרכזי בריאות הנפש', 'rehabilitation', ARRAY['rehabilitation', 'youth']::text[]),
  ('מכון_צוהר_73', 'מכון צוהר', 'נתיבי שיקום והחלמה', 'rehabilitation', ARRAY['rehabilitation']::text[]),
  ('חברת_נתן_74', 'חברת נתן', 'שיקום ובריאות הנפש', 'rehabilitation', ARRAY['rehabilitation']::text[]),
  ('רקליני_הבית_לטיפולים_קליניים_37', 'רקליני - הבית לטיפולים קליניים', 'אינדקס מטפלים', 'therapists', ARRAY['therapists']::text[]),
  ('על_הספה_30', 'על הספה', 'אינדקס מטפלים (כולל פסיכיאטרים)', 'therapists', ARRAY['therapists']::text[]),
  ('פסיכולוגיה_עברית_31', 'פסיכולוגיה עברית', 'אינדקס מטפלים (כולל פסיכיאטרים)', 'therapists', ARRAY['therapists']::text[]),
  ('בטיפולנט_32', 'בטיפולנט', 'אינדקס מטפלים (כולל פסיכיאטרים)', 'therapists', ARRAY['therapists']::text[]),
  ('טל_הנפש_49', 'טל הנפש', 'התאגדות המטפלים הדתיים', 'therapists', ARRAY['therapists', 'populations']::text[]),
  ('מכון_למרחב_מרכז_טיפולי_רב_תחומי_65', 'מכון למרחב
(מרכז טיפולי רב תחומי)', 'מענה מקצועי מותאם תרבות בתחום בריאות הנפש לאוכלוסיה הדתית - חרדית.', 'therapists', ARRAY['therapists', 'treatments', 'treatments_therapy', 'populations']::text[]),
  ('relief_resources_81', 'Relief Resources', 'Help finding qualified mental health providers for English-speakers', 'therapists', ARRAY['therapists', 'populations']::text[]),
  ('חיים_של_טובה_96', 'חיים של טובה', 'הכוונה לטיפול הפסיכולוגי המתאים לכם וסבסוד טיפולים', 'therapists', ARRAY['therapists']::text[]),
  ('me_mental_experts_90', 'ME-MENTAL EXPERTS', 'מרכזים לטיפול רגשי', 'therapists', ARRAY['therapists']::text[]),
  ('medreviews_33', 'MEDREVIEWS', 'אינדקס פסיכיאטרים', 'therapists', ARRAY['therapists']::text[]),
  ('אינפומד_34', 'אינפומד', 'אינדקס פסיכיאטרים', 'therapists', ARRAY['therapists']::text[]),
  ('אימפולס_מרכז_קליני_אינטגרטיבי_88', 'אימפולס - מרכז קליני אינטגרטיבי', 'מרכז לפסיכותרפיה אינטגרטיבית. תמיכה נפשית, רגשית ורוחנית דרך מגוון רחב של גישות ועל ידי אנשי מקצוע מוסמכים', 'therapists', ARRAY['therapists']::text[]),
  ('איט_ה_האגודה_הישראלית_לטיפול_קוגניטיבי_התנהגותי_cbt_50', 'איט"ה האגודה הישראלית לטיפול קוגניטיבי התנהגותי - CBT', 'אינדקס מטפלים', 'therapists', ARRAY['therapists', 'treatments', 'treatments_therapy']::text[]),
  ('טיפול_סומטי_somatic_experiencing_51', 'טיפול סומטי 
Somatic Experiencing', 'אינדקס מטפלים', 'therapists', ARRAY['therapists', 'treatments', 'treatments_therapy', 'trauma']::text[]),
  ('מיינדמי_mindme_104', 'מיינדמי (MindMe)', 'מרכז פסיכיאטרי וטיפול רגשי: פסיכותרפיה, טיפול קוגניטיבי-התנהגותי (CBT), טיפול זוגי ומשפחתי, פסיכיאטריה ומתן תרופות, EMDR/DBT/NLP, חרדה, דיכאון, טראומה, התמכרויות ועוד', 'treatments', ARRAY['treatments', 'treatments_psychiatry', 'local']::text[]),
  ('kav_l_noar_merchav_l_noar_102', 'Kav L''Noar (Merchav L''Noar)', 'Therapy clinic for teenagers & young adults (11-27) and parents; specializes in Anglo olim; Halachik framework; therapy for individuals, couples and families', 'treatments', ARRAY['treatments', 'treatments_therapy', 'youth', 'populations']::text[]),
  ('חיים_של_טובה_96', 'חיים של טובה', 'הכוונה לטיפול הפסיכולוגי המתאים וסבסוד טיפולים פסיכולוגיים', 'treatments', ARRAY['treatments', 'treatments_therapy']::text[]),
  ('המרכז_הישראלי_להתמכרויות_89', 'המרכז הישראלי להתמכרויות', 'טיפול והתמודדות עם התמכרויות', 'treatments', ARRAY['treatments', 'treatments_others']::text[]),
  ('tms_deep_tms_105', 'TMS / Deep TMS', 'טיפולי גרייה מוחית (TMS ו-Deep TMS) למגוון מצבים נפשיים ונוירולוגיים.', 'treatments', ARRAY['treatments', 'treatments_others']::text[]),
  ('psychedelic_treatment_therapy_106', 'Psychedelic Treatment & Therapy', 'מרכז גישה לטיפול ותרפיה פסיכדלית.', 'treatments', ARRAY['treatments', 'treatments_others']::text[]),
  ('psychedelic_therapy_107', 'Psychedelic Therapy', 'טיפול פסיכדלי ומידע מקצועי בתחום.', 'treatments', ARRAY['treatments', 'treatments_others']::text[]),
  ('tms_גרייה_מגנטית_מוחית_108', 'TMS (גרייה מגנטית מוחית)', 'טיפול בגרייה מגנטית מוחית (TMS) במסגרת מרפאה פסיכיאטרית.', 'treatments', ARRAY['treatments', 'treatments_others']::text[]),
  ('ect_נזעי_חשמל_109', 'ECT (נזעי חשמל)', 'מידע על טיפול בנזעי חשמל (ECT) במסגרת פסיכיאטרית.', 'treatments', ARRAY['treatments', 'treatments_others']::text[]),
  ('המרכז_הישראלי_להתמכרויות_ica_94', 'המרכז הישראלי להתמכרויות (ICA)', 'מרכז לאומי מוביל לצמצום תופעת ההתמכרויות ונזקיה. טיפול, מידע והכוונה למי שמתמודד עם התמכרות', 'addictions', ARRAY['addictions']::text[]),
  ('מרכז_גמילה_המרכז_ההוליסטי_אחרת_95', 'מרכז גמילה - המרכז ההוליסטי "אחרת"', 'מרכז גמילה הוליסטי לטיפול בהתמכרויות (סמים, אלכוהול, הימורים ועוד) המבוסס על 12 הצעדים וגישות טיפוליות נוספות', 'addictions', ARRAY['addictions']::text[]),
  ('cptsd_פוסט_טראומה_מורכבת_56', 'CPTSD - פוסט טראומה מורכבת', 'קבוצה בפייסבוק', 'trauma', ARRAY['trauma', 'facebook']::text[]),
  ('דיאלוג_פתוח_בישראל_דפי_69', 'דיאלוג פתוח בישראל (דפי)', 'טיפול משפחתי-מערכתי למצבי משבר', 'families', ARRAY['families']::text[]),
  ('חיים_של_טובה_96', 'חיים של טובה', 'הכוונה לטיפול הפסיכולוגי המתאים לכם, סבסוד טיפולים, חוסן משפחתי. שינוי מפת ההתמודדות המשפחתית והקהילתית במצבי מצוקה אישיים ומשפחתיים.', 'families', ARRAY['families']::text[]),
  ('amudim_80', 'Amudim', 'Clinical case management for English-speakers in Israel from all walks of life: counseling, referrals to therapists, treatment programs, guidance through the legal process', 'populations', ARRAY['populations']::text[]),
  ('מטפלים_וטיפולים_55', 'מטפלים וטיפולים', 'קבוצה בפייסבוק', 'facebook', ARRAY['facebook']::text[]),
  ('מתייעצים_עם_פסיכולוגים_ופסיכותרפיסטים_54', 'מתייעצים עם פסיכולוגים ופסיכותרפיסטים', 'קבוצה בפייסבוק', 'facebook', ARRAY['facebook']::text[]),
  ('המלצות_ואזהרות_על_פסיכיאטרים_מטפלים_ושירותי_בריאות_הנפש_86', 'המלצות ואזהרות על פסיכיאטרים, מטפלים ושירותי בריאות הנפש', 'קבוצה בפייסבוק', 'facebook', ARRAY['facebook']::text[]),
  ('ייעוץ_פסיכולוגי_שאלות_למטפלים_פסיכולוגים_58', 'ייעוץ פסיכולוגי - שאלות למטפלים פסיכולוגים', 'קבוצה בפייסבוק', 'facebook', ARRAY['facebook']::text[]),
  ('אפליקציית_rescue_101', 'אפליקציית Rescue', 'אפליקציה חינמית המספקת עזרה ראשונה נפשית ותמיכה מיידית בזמן התקף חרדה, ומלווה את המשתמש עד חזרה הדרגתית לשגרה.', 'anxiety_apps', ARRAY['anxiety_apps']::text[]),
  ('vivid_the_flexible_app_for_life_changing_practices_102', 'VIVID - The Flexible App for Life-Changing Practices', 'אפליקציה אינטראקטיבית לבניית תוכניות תרגול יומי ומעקב לאורך זמן.', 'anxiety_apps', ARRAY['anxiety_apps']::text[]),
  ('המדריך_ל_ptsd_103', 'המדריך ל-PTSD', 'אפליקציה/מדריך דיגיטלי להתמודדות עם PTSD, מטעם אגף השיקום (משרד הביטחון).', 'anxiety_apps', ARRAY['anxiety_apps']::text[]),
  ('ענת_אופיר_87', 'ענת אופיר', 'מומחית בהפרעות אכילה/תזונה/כושר/דיאטה, מטפלת בפגועי נפש עם רישיון. בעלות סימלית, חברות ביטוח מחזירות', 'nutrition', ARRAY['nutrition']::text[]),
  ('hakshiva_therapy_clinic_הקשיבה_91', 'Hakshiva Therapy Clinic - הקשיבה', 'Therapy for teenagers, couples therapy and parenting guidance', 'local', ARRAY['local']::text[]),
  ('חבלי_קשר_hevlei_kesher_92', 'חבלי קשר - Hevlei Kesher', 'דיכאון אחרי לידה ועוד, דרך טיפת חלב בירושלים
Support and treatment for Maternal Mental Health through Tipat Halav. Services for mothers and families impacted by perinatal mental health disorders (PMHD) such as postpartum depression', 'local', ARRAY['local']::text[]),
  ('modi_in_behavioral_93', 'Modi''in Behavioral', 'CBT, DBT, and Exposure-Based Therapies', 'local', ARRAY['local']::text[]),
  ('עזר_מציון_הסעות_83', 'עזר מציון הסעות', 'הסעות חולים, אמבולנסים, נהגים מתנדבים', 'transport', ARRAY['transport']::text[]),
  ('לב_מלכה_84', 'לב מלכה', 'סיוע באמבולנסים בהעברת חולים ונכים', 'transport', ARRAY['transport']::text[]);
