-- Numbered migrations (newest first — add new lines at the top after each migration).
[x] 020_directory_entries_mapalanefesh_ngos.sql
[x] 019_directory_entries_mapalanefesh.sql
[x] 018_directory_entries_malkishua.sql
[x] 017_directory_entries_addiction_orgs.sql
[x] 016_directory_entries_ezra_lemarpe.sql
[x] 015_directory_entries_ambulance_services.sql
[x] 014_events_allow_section_link_event_types.sql
[x] 013_directory_entries_salshikum.sql
[x] 012_events_allow_deep_link_event_types.sql
[x] 011_directory_entries_mh_clinics_section.sql
[x] 010_directory_entries_haravot_barzel_patch.sql
[x] 009_directory_entries_haravot_barzel_orgs.sql
[x] 008_directory_entries_haravot_barzel_categories.sql
[x] 007_directory_entries_haravot_barzel.sql
[x] 006_directory_entries_anat_rusman.sql
[x] 005_directory_entries_mishpachot.sql
[x] 004_directory_entries_emergency_local_patch.sql
[x] 003_directory_entries_resources_may_2026.sql
[x] 002_directory_entries_tms_title_updates.sql
[x] 001_directory_entries_treatments_subsections.sql
