#!/usr/bin/env node
/**
 * Regenerates docs/facet-coverage.md from DATA + referral_codes.json.
 *
 * Coverage is a measurement, not a claim. Re-run after any backfill:
 *   node scripts/facet_coverage.js
 */
const fs = require('fs');
const path = require('path');
const { load } = require('./lib/extract_data');

const ROOT = path.join(__dirname, '..');

function unique(entries) {
  const seen = new Set();
  return entries.filter((e) => {
    if (seen.has(e.row)) return false;
    seen.add(e.row);
    return true;
  });
}

function filled(entries, pred) {
  const n = entries.filter(pred).length;
  return { n, pct: entries.length ? (100 * n) / entries.length : 0 };
}

function fmt({ n, pct }, total) {
  return `${n}/${total} (${pct.toFixed(1)}%)`;
}

function main() {
  const data = load();
  const entries = unique(data.entries);
  const total = entries.length;

  const cost = filled(entries, (e) => Boolean((e.raw.cost || '').trim()));
  const region = filled(entries, (e) => Boolean((e.raw.region || '').trim()));
  const target = filled(entries, (e) => Boolean((e.raw.target || '').trim()));
  const referralKnown = filled(entries, (e) => {
    const codes = e.raw.referralCodes || [];
    return codes.length > 0 && !(codes.length === 1 && codes[0] === 'unknown');
  });
  const referralAny = filled(entries, (e) => Array.isArray(e.raw.referralCodes) && e.raw.referralCodes.length > 0);

  const TREAT = new Set(['therapists', 'treatments', 'hmo', 'mh_clinics', 'hospitalization', 'alternatives', 'addictions', 'trauma', 'nutrition']);
  const RIGHTS = new Set(['rights', 'moh', 'mod', 'rehabilitation']);
  const scoped = unique(entries.filter((e) => e.categories.some((c) => TREAT.has(c) || RIGHTS.has(c))));
  const scopedKnown = filled(scoped, (e) => {
    const codes = e.raw.referralCodes || [];
    return codes.length > 0 && !(codes.length === 1 && codes[0] === 'unknown');
  });

  const md = `# Facet coverage

Generated by \`scripts/facet_coverage.js\` on ${new Date().toISOString().slice(0, 10)}. Do not hand-edit the numbers.

Unique entries: **${total}**. Treatment + rights groups: **${scoped.length}**.

Free-text fields are counted as present when non-empty. \`referral_route\` is counted as known when a code other than \`unknown\` has been assigned. Source wording is never discarded — codes sit alongside \`notes\` / \`cost\` / \`target\`.

| Facet | Before (plan, 2026-09-08) | After this backfill |
|---|---|---|
| cost (free text) | 57/197 (29%) | ${fmt(cost, total)} |
| region (free text) | 108/197 (55%) | ${fmt(region, total)} |
| target (free text) | 45/197 (23%) | ${fmt(target, total)} |
| referral_route (any code, including unknown) | 0/197 (0%) | ${fmt(referralAny, total)} |
| referral_route (known, not unknown) | 0/197 (0%) | ${fmt(referralKnown, total)} |
| referral_route known, treatment + rights only | 0 | ${fmt(scopedKnown, scoped.length)} |

Targets from the plan (not yet met, and not claimed): 80% for funding_model and district, 60% for referral_route site-wide. The Phase 3 slice only backfills treatment and rights.

**What this licenses:** "Referral route is a controlled vocabulary with measured coverage of ${fmt(referralKnown, total)} site-wide and ${fmt(scopedKnown, scoped.length)} in the treatment and rights groups, and the original published wording is preserved."

**What this does not license:** that the codes are complete, authoritative, or that a missing badge means self-referral. Unknown means the source did not say.
`;

  const dest = path.join(ROOT, 'docs', 'facet-coverage.md');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, md, 'utf8');
  console.log(md);
  console.log(`Wrote ${dest}`);
}

if (require.main === module) main();
