/**
 * Writes scripts/045_directory_card_edits.sql from index.html DATA.
 * INSERT … ON CONFLICT DO NOTHING, so running it again does not overwrite admin edits.
 *
 * Usage: node scripts/seed_directory_card_edits.js
 */

const fs = require('fs');
const path = require('path');
const ts = require('typescript');
const { load, evaluateLiterals, getEntryId } = require('./lib/extract_data');

const OUT_PATH = path.join(__dirname, '045_directory_card_edits.sql');

function loadCardModule() {
  const srcPath = path.join(__dirname, '..', 'lib', 'directory-cards.ts');
  const src = fs.readFileSync(srcPath, 'utf8');
  const { outputText } = ts.transpileModule(src, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
      esModuleInterop: true,
    },
    fileName: srcPath,
  });
  const moduleObj = { exports: {} };
  const fn = new Function('exports', 'require', 'module', outputText);
  fn(moduleObj.exports, require, moduleObj);
  return moduleObj.exports;
}

function sqlLiteral(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function cardKeyOf(raw) {
  return `${raw.row}|||${raw.svc || ''}`;
}

const DDL = `-- Admin-editable directory card text and hidden eligibility.
-- Seed generated by: node scripts/seed_directory_card_edits.js
-- ON CONFLICT DO NOTHING so a re-run does not overwrite admin edits.
--
-- eligibility: empty / any means no constraint on that dimension. A set value is
-- necessary but not sufficient for a future care-file matcher. Not painted on the
-- card. The public directory API returns it, and the page writes set values into JSON-LD.
-- There is no משרד הבריאות flag on the care file yet; recognition.moh can still be
-- marked required here.

CREATE TABLE IF NOT EXISTS directory_card_edits (
  id serial PRIMARY KEY,
  card_key text NOT NULL UNIQUE,
  row_id integer NOT NULL,
  entry_id text,
  public_fields jsonb NOT NULL,
  eligibility jsonb NOT NULL,
  public_edited_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT directory_card_edits_card_key_len CHECK (char_length(card_key) BETWEEN 1 AND 800),
  CONSTRAINT directory_card_edits_public_object CHECK (jsonb_typeof(public_fields) = 'object'),
  CONSTRAINT directory_card_edits_eligibility_object CHECK (jsonb_typeof(eligibility) = 'object'),
  CONSTRAINT directory_card_edits_notes_len CHECK (
    char_length(COALESCE(eligibility->>'internal_notes', '')) <= 4000
  )
);

CREATE INDEX IF NOT EXISTS directory_card_edits_row_idx ON directory_card_edits (row_id);

COMMENT ON TABLE directory_card_edits IS
  'Admin-edited visible card text (public_fields) and hidden eligibility. card_key is row|||svc from DATA at seed time and does not change when the visible subtitle is edited.';

COMMENT ON COLUMN directory_card_edits.eligibility IS
  'Match rules. any/empty = no constraint. A set value is necessary but not sufficient. Returned by the public directory API and published as JSON-LD, not painted on the card.';

COMMENT ON COLUMN directory_card_edits.public_edited_at IS
  'Set only when an admin changes visible card text. Eligibility-only saves leave it null so the public footer date does not move.';
`;

function main() {
  const { normalizePublicFields, emptyEligibility } = loadCardModule();
  const loaded = load();
  const byKey = new Map();

  const add = (raw, categoryKey) => {
    if (!raw || raw.row == null || raw.row === '') return;
    const rowId = Number(raw.row);
    if (!Number.isInteger(rowId)) {
      console.warn('skip non-integer row', raw.row, raw.org);
      return;
    }
    const key = cardKeyOf(raw);
    if (byKey.has(key)) return;
    let publicFields;
    try {
      publicFields = normalizePublicFields(raw);
    } catch (err) {
      console.warn('skip', key, err.message);
      return;
    }
    byKey.set(key, {
      cardKey: key,
      rowId,
      entryId: getEntryId(raw, categoryKey || 'emergency'),
      publicFields,
    });
  };

  for (const entry of loaded.entries) add(entry.raw, entry.categories[0] || 'emergency');

  const booklet = evaluateLiterals(loaded.html, ['HARAVOT_BARZEL_SEARCH', 'HARAVOT_BARZEL_BOOKLET'])
    .HARAVOT_BARZEL_BOOKLET;
  if (booklet) add(booklet, 'emergency');

  const eligibility = emptyEligibility();
  const eligibilitySql = `${sqlLiteral(JSON.stringify(eligibility))}::jsonb`;
  const rows = [...byKey.values()].sort((a, b) => a.rowId - b.rowId || a.cardKey.localeCompare(b.cardKey));

  const chunks = [];
  const size = 40;
  for (let i = 0; i < rows.length; i += size) {
    const part = rows.slice(i, i + size);
    const values = part
      .map(
        (row) =>
          `  (${sqlLiteral(row.cardKey)}, ${row.rowId}, ${sqlLiteral(row.entryId)}, ${sqlLiteral(JSON.stringify(row.publicFields))}::jsonb, ${eligibilitySql})`
      )
      .join(',\n');
    chunks.push(
      `INSERT INTO directory_card_edits (card_key, row_id, entry_id, public_fields, eligibility)\nVALUES\n${values}\nON CONFLICT (card_key) DO NOTHING;`
    );
  }

  const sql = `${DDL}\n${chunks.join('\n\n')}\n`;
  fs.writeFileSync(OUT_PATH, sql);
  console.log(`wrote ${rows.length} cards to ${path.relative(process.cwd(), OUT_PATH)}`);
}

main();
